/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ErrorMessageError } from '../errors/errorMessageError';
import {
  LoanPaymentDetails,
  loanPaymentDetailsSchema,
} from '../models/loanPaymentDetails';
import { string } from '../schema';
import { BaseController } from './baseController';

export class LiabilitiesController extends BaseController {
  /**
   * Return the loan payment details of the customer for a loan-type account.
   *
   * Note: this is a premium service, billable per every successful API call.
   *
   * _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
   *
   * @param customerId A Finicity customer ID
   * @param accountId  The account ID
   * @return Response from the API call
   */
  async getLoanPaymentDetails(
    customerId: string,
    accountId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LoanPaymentDetails>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      customerId: [customerId, string()],
      accountId: [accountId, string()],
    });
    req.appendTemplatePath`/aggregation/v2/customers/${mapped.customerId}/accounts/${mapped.accountId}/loanDetails`;
    req.throwOn(400, ErrorMessageError, 'The request was rejected');
    req.throwOn(401, ErrorMessageError, 'The request lacks valid authentication credentials. Check "Finicity-App-Key" or "Finicity-App-Token".');
    req.throwOn(404, ErrorMessageError, 'The resource doesn\'t exist');
    return req.callAsJson(loanPaymentDetailsSchema, requestOptions);
  }
}
