/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** A temporary access token to be passed in the `Finicity-App-Token` HTTP header of all subsequent API requests */
export interface AccessToken {
  /** The access token value */
  token: string;
}

export const accessTokenSchema: Schema<AccessToken> = object({
  token: ['token', string()],
});
