/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

/** Owner of a customer account */
export interface AccountOwner {
  /** The name of the account owner. Can be multiple account owners in one string. This is how the source data is returned from the institution. */
  ownerName: string;
  /** A street address */
  ownerAddress: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  asOfDate?: bigint;
}

export const accountOwnerSchema: Schema<AccountOwner> = object({
  ownerName: ['ownerName', string()],
  ownerAddress: ['ownerAddress', string()],
  asOfDate: ['asOfDate', optional(bigint())],
});
