/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The routing and account number information to initiate ACH transfers */
export interface ACHDetails {
  /** The routing number of the financial institution for this specific customers account */
  routingNumber: string;
  /** The account number for initiating ACH transfers for this account */
  realAccountNumber: string;
}

export const aCHDetailsSchema: Schema<ACHDetails> = object({
  routingNumber: ['routingNumber', string()],
  realAccountNumber: ['realAccountNumber', string()],
});
