/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  AppFinancialInstitutionStatus,
  appFinancialInstitutionStatusSchema,
} from './appFinancialInstitutionStatus';

/** Registration status details for the application */
export interface AppStatus {
  /** Your Partner ID displayed in the [Developer Dashboard](https://developer.finicity.com/admin) */
  partnerId: string;
  /** Identifier to track the application registration from the "App Registration" and "Get App Registration Status" endpoints */
  preAppId: string;
  /** A note on the registration. Typically used to indicate reasons for rejected apps. */
  note?: string;
  /** `applicationId` value returned from the "Get App Registration Status" endpoint and the partner assign the customers to. This cannot be changed once set. Only applicable in cases of partners with multiple registered applications. If the partner only has one app, this can usually be omitted. This field is populated after the app is in a status approved. */
  applicationId?: string;
  /** The name of the application assigned to the customer */
  appName: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  submittedDate: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  modifiedDate: bigint;
  /** The status of an app registration request. "A" means approved. "P" means pending which is the status when initially submitted or when the app is modified and awaiting approval. "R" means rejected. If it is rejected there will be a note with the rejected reason. */
  status: string;
  /** Indicates scopes of data accessible to the app */
  scopes?: string;
  /** A list of the registration status for each FI for the application */
  institutionDetails?: AppFinancialInstitutionStatus[];
}

export const appStatusSchema: Schema<AppStatus> = object({
  partnerId: ['partnerId', string()],
  preAppId: ['preAppId', string()],
  note: ['note', optional(string())],
  applicationId: ['applicationId', optional(string())],
  appName: ['appName', string()],
  submittedDate: ['submittedDate', bigint()],
  modifiedDate: ['modifiedDate', bigint()],
  status: ['status', string()],
  scopes: ['scopes', optional(string())],
  institutionDetails: [
    'institutionDetails',
    optional(array(lazy(() => appFinancialInstitutionStatusSchema))),
  ],
});
