/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, Schema } from '../schema';
import { AppStatus, appStatusSchema } from './appStatus';

/** The response for the "Get App Registration Status" endpoint which returns an array of status objects */
export interface AppStatuses {
  /** The total number of results */
  totalRecords: bigint;
  /** The total number of pages */
  totalPages: bigint;
  /** The current page number */
  pageNumber: bigint;
  /** The number of results per page */
  numberOfRecordsPerPage: bigint;
  /** A list of applications with their statuses */
  applications: AppStatus[];
}

export const appStatusesSchema: Schema<AppStatuses> = object({
  totalRecords: ['totalRecords', bigint()],
  totalPages: ['totalPages', bigint()],
  pageNumber: ['pageNumber', bigint()],
  numberOfRecordsPerPage: ['numberOfRecordsPerPage', bigint()],
  applications: ['applications', array(lazy(() => appStatusSchema))],
});
