/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** A Finicity asset */
export interface Asset {
  /** A Finicity asset ID. Generated by Connect or by using the "Store Customer Pay Statement" API. */
  assetId: string;
}

export const assetSchema: Schema<Asset> = object({
  assetId: ['assetId', string()],
});
