/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, Schema, string } from '../schema';

export interface AvailableBalance {
  /** A Finicity customer ID represented as a number. See also: "Add Customer". */
  id: bigint;
  /** The last 4 digits of the ACH account number */
  realAccountNumberLast4: string;
  /** The available balance of the account */
  availableBalance: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  availableBalanceDate: bigint;
  /** The cleared balance of the account. Also referred as posted balance, current balance, ledger balance */
  clearedBalance: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  clearedBalanceDate: bigint;
  /** The status of the most recent aggregation attempt (see [Aggregation Status Codes](https://docs.finicity.com/aggregation-status-codes/)). Won't be present until you have run your first aggregation for the account. */
  aggregationStatusCode: number;
  /** A currency code */
  currency: string;
}

export const availableBalanceSchema: Schema<AvailableBalance> = object({
  id: ['id', bigint()],
  realAccountNumberLast4: ['realAccountNumberLast4', string()],
  availableBalance: ['availableBalance', number()],
  availableBalanceDate: ['availableBalanceDate', bigint()],
  clearedBalance: ['clearedBalance', number()],
  clearedBalanceDate: ['clearedBalanceDate', bigint()],
  aggregationStatusCode: ['aggregationStatusCode', number()],
  currency: ['currency', string()],
});
