/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** A birth date */
export interface Birthday {
  /** The birthday 4-digit year */
  year?: number;
  /** The birthday 2-digit month (1 is January) */
  month?: number;
  /** The birthday 2-digit day-of-month */
  dayOfMonth?: number;
}

export const birthdaySchema: Schema<Birthday> = object({
  year: ['year', optional(number())],
  month: ['month', optional(number())],
  dayOfMonth: ['dayOfMonth', optional(number())],
});
