/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BorrowerTypeEnum
 */
export enum BorrowerTypeEnum {
  Primary = 'primary',
  JointBorrower = 'jointBorrower',
}

/**
 * Schema for BorrowerTypeEnum
 */
export const borrowerTypeEnumSchema: Schema<BorrowerTypeEnum> = stringEnum(BorrowerTypeEnum);
