/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { BorrowerTypeEnum, borrowerTypeEnumSchema } from './borrowerTypeEnum';
import { ConsumerInfo, consumerInfoSchema } from './consumerInfo';

export interface Borrower {
  /** A Finicity customer ID. See also: "Add Customer". */
  customerId: string;
  /** A Finicity consumer ID. See also: "Create Consumer". */
  consumerId: string;
  type: BorrowerTypeEnum;
  /** The SSN and date of birth of a consumer */
  optionalConsumerInfo?: ConsumerInfo;
}

export const borrowerSchema: Schema<Borrower> = object({
  customerId: ['customerId', string()],
  consumerId: ['consumerId', string()],
  type: ['type', borrowerTypeEnumSchema],
  optionalConsumerInfo: [
    'optionalConsumerInfo',
    optional(lazy(() => consumerInfoSchema)),
  ],
});
