/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Branding, brandingSchema } from './branding';

export interface BrandingWrapper {
  /** All assets are SVGs so can be slightly resized without any issues. */
  branding: Branding;
}

export const brandingWrapperSchema: Schema<BrandingWrapper> = object({
  branding: ['branding', lazy(() => brandingSchema)],
});
