/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ChildInstitution, childInstitutionSchema } from './childInstitution';

export interface CertifiedInstitution {
  /** The ID of a financial institution, represented as a number */
  id: bigint;
  /** The RSSD ID is a unique identifier assigned to financial institutions by the Federal Reserve. While the length of the RSSD ID varies by institution, it cannot exceed 10 numerical digits. */
  rssd?: bigint;
  /** The name of the institution */
  name: string;
  /**
   * `true`: The institution is certified for the Transaction Aggregation product
   * `false`: The institution is decertified for the Transaction Aggregation product
   */
  transAgg: boolean;
  /**
   * `true`: The institution is certified for the ACH product
   * `false`: The institution is decertified for the ACH product
   */
  ach: boolean;
  /**
   * `true`: The institution is certified for the Statement Aggregation product
   * `false`: The institution is decertified for the Statement Aggregation product
   */
  stateAgg: boolean;
  /**
   * `true`: The institution is certified for the VOI product
   * `false`: The institution is decertified for the VOI product
   */
  voi: boolean;
  /**
   * `true`: The institution is certified for the VOA product
   * `false`: The institution is decertified for the VOA product
   */
  voa: boolean;
  /**
   * `true`: The institution is certified for the Account History Aggregation product
   * `false`: The institution is decertified for the Account History Aggregation product
   */
  aha: boolean;
  /**
   * `true`: The institution is certified for the Account Balance Check (ABC) product
   * `false`: The institution is decertified for the Account Balance Check product
   */
  availBalance: boolean;
  /**
   * `true`: The institution is certified for the Account Owner product
   * `false`: The institution is decertified for the Account Owner product
   */
  accountOwner: boolean;
  /** An array of child financial institutions */
  childInstitutions?: ChildInstitution[];
}

export const certifiedInstitutionSchema: Schema<CertifiedInstitution> = object({
  id: ['id', bigint()],
  rssd: ['rssd', optional(bigint())],
  name: ['name', string()],
  transAgg: ['transAgg', boolean()],
  ach: ['ach', boolean()],
  stateAgg: ['stateAgg', boolean()],
  voi: ['voi', boolean()],
  voa: ['voa', boolean()],
  aha: ['aha', boolean()],
  availBalance: ['availBalance', boolean()],
  accountOwner: ['accountOwner', boolean()],
  childInstitutions: [
    'childInstitutions',
    optional(array(lazy(() => childInstitutionSchema))),
  ],
});
