/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, boolean, lazy, number, object, Schema } from '../schema';
import {
  CertifiedInstitution,
  certifiedInstitutionSchema,
} from './certifiedInstitution';

/** A list of Finicity financial institutions from the "Get Certified Institutions" API */
export interface CertifiedInstitutions {
  /** The total number of results matching search criteria */
  found: number;
  /** The number of results returned */
  displaying: number;
  /** If `true`, you can fetch the next page of results */
  moreAvailable: boolean;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  requestedDate: bigint;
  /** A list of institutions */
  institutions: CertifiedInstitution[];
}

export const certifiedInstitutionsSchema: Schema<CertifiedInstitutions> = object(
  {
    found: ['found', number()],
    displaying: ['displaying', number()],
    moreAvailable: ['moreAvailable', boolean()],
    requestedDate: ['requestedDate', bigint()],
    institutions: [
      'institutions',
      array(lazy(() => certifiedInstitutionSchema)),
    ],
  }
);
