/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** An analytic ID and a date */
export interface ConsumerAttributesAnalyticId {
  /** An ID for a Consumer Attributes report */
  analyticId: string;
  /** A date-time without time zone */
  createdDate: string;
}

export const consumerAttributesAnalyticIdSchema: Schema<ConsumerAttributesAnalyticId> = object(
  {
    analyticId: ['analytic_id', string()],
    createdDate: ['created_date', string()],
  }
);
