/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

/** The SSN and date of birth of a consumer */
export interface ConsumerInfo {
  /** A full SSN without hyphens */
  ssn: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  dob?: bigint;
}

export const consumerInfoSchema: Schema<ConsumerInfo> = object({
  ssn: ['ssn', string()],
  dob: ['dob', optional(bigint())],
});
