/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, object, optional, Schema, string } from '../schema';
import { Birthday, birthdaySchema } from './birthday';

/** A finicity consumer record */
export interface Consumer {
  /** A Finicity consumer ID. See also: "Create Consumer". */
  id: string;
  /** First name(s) / given name(s) */
  firstName: string;
  /** Last name(s) / surname(s) */
  lastName: string;
  /** A Finicity customer ID represented as a number. See also: "Add Customer". */
  customerId: bigint;
  /** A street address */
  address: string;
  /** A city */
  city: string;
  /** A state */
  state: string;
  /** A ZIP code */
  zip: string;
  /** A phone number */
  phone: string;
  /** Last 4 digits of a SSN */
  ssn: string;
  /** A birth date */
  birthday: Birthday;
  /** An email address */
  email: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  createdDate: bigint;
  /** A person suffix */
  suffix?: string;
}

export const consumerSchema: Schema<Consumer> = object({
  id: ['id', string()],
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  customerId: ['customerId', bigint()],
  address: ['address', string()],
  city: ['city', string()],
  state: ['state', string()],
  zip: ['zip', string()],
  phone: ['phone', string()],
  ssn: ['ssn', string()],
  birthday: ['birthday', lazy(() => birthdaySchema)],
  email: ['email', string()],
  createdDate: ['createdDate', bigint()],
  suffix: ['suffix', optional(string())],
});
