/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  ConsumerAttributesAnalyticId,
  consumerAttributesAnalyticIdSchema,
} from './consumerAttributesAnalyticId';

export interface ConsumerAttributeList {
  /** A list of analytic IDs */
  analyticIds: ConsumerAttributesAnalyticId[];
}

export const consumerAttributeListSchema: Schema<ConsumerAttributeList> = object(
  {
    analyticIds: [
      'analytic_ids',
      array(lazy(() => consumerAttributesAnalyticIdSchema)),
    ],
  }
);
