/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  ConsumerAttributesDataAssets,
  consumerAttributesDataAssetsSchema,
} from './consumerAttributesDataAssets';
import {
  ConsumerAttributesDataDateRange,
  consumerAttributesDataDateRangeSchema,
} from './consumerAttributesDataDateRange';
import {
  ConsumerAttributesDataExpenses,
  consumerAttributesDataExpensesSchema,
} from './consumerAttributesDataExpenses';
import {
  ConsumerAttributesDataIncome,
  consumerAttributesDataIncomeSchema,
} from './consumerAttributesDataIncome';
import {
  ConsumerAttributesDataLiabilities,
  consumerAttributesDataLiabilitiesSchema,
} from './consumerAttributesDataLiabilities';
import {
  ConsumerAttributesDataNetAmount,
  consumerAttributesDataNetAmountSchema,
} from './consumerAttributesDataNetAmount';
import {
  ConsumerAttributesDataNSF,
  consumerAttributesDataNSFSchema,
} from './consumerAttributesDataNSF';

export interface ConsumerAttributesData {
  dateRange: ConsumerAttributesDataDateRange;
  income: ConsumerAttributesDataIncome;
  expenses: ConsumerAttributesDataExpenses;
  netAmount: ConsumerAttributesDataNetAmount;
  nsf: ConsumerAttributesDataNSF;
  assets: ConsumerAttributesDataAssets;
  liabilities: ConsumerAttributesDataLiabilities;
}

export const consumerAttributesDataSchema: Schema<ConsumerAttributesData> = object(
  {
    dateRange: ['dateRange', lazy(() => consumerAttributesDataDateRangeSchema)],
    income: ['income', lazy(() => consumerAttributesDataIncomeSchema)],
    expenses: ['expenses', lazy(() => consumerAttributesDataExpensesSchema)],
    netAmount: ['netAmount', lazy(() => consumerAttributesDataNetAmountSchema)],
    nsf: ['nsf', lazy(() => consumerAttributesDataNSFSchema)],
    assets: ['assets', lazy(() => consumerAttributesDataAssetsSchema)],
    liabilities: [
      'liabilities',
      lazy(() => consumerAttributesDataLiabilitiesSchema),
    ],
  }
);
