/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, unknown } from '../schema';

export interface ConsumerAttributesDataNSF {
  /** The number of non-sufficient funds occurrences per calendar month. */
  monthlyNSFOccurrences?: unknown;
  /** The number of late fee occurrences. */
  monthlyLateFeeOccurrences: number;
}

export const consumerAttributesDataNSFSchema: Schema<ConsumerAttributesDataNSF> = object(
  {
    monthlyNSFOccurrences: ['monthlyNSFOccurrences', optional(unknown())],
    monthlyLateFeeOccurrences: ['monthlyLateFeeOccurrences', number()],
  }
);
