/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface ConsumerAttributesAssetsCustomer {
  /** The minimum balance for the month across all customer accounts. */
  monthlyMinimumBalance?: unknown;
  /** The maximum balance for the month across all customer accounts. */
  monthlyMaximumBalance?: unknown;
  /** The average balance for the month across all customer accounts. */
  monthlyAverageBalance?: unknown;
  /** The standard deviation for the month across all customer account balances. */
  monthlyStandardDeviationOfBalance?: unknown;
  /** The number of days in a month with a positive account balance across all customer account balances. */
  monthlyDaysWithPositiveBalance?: unknown;
  /** The number of days in a month with a negative account balance across all customer account balances. */
  monthlyDaysWithNegativeBalance?: unknown;
  /** Customer average balance for two months. */
  monthlyTwoMonthAverageBalance?: unknown;
  /** Customer average balance for six months. */
  monthlySixMonthAverageBalance?: unknown;
  /** Customer average balance for twelve months. */
  twelveMonthAverageBalance?: unknown;
  /** Two month standard deviation of customer balance. */
  twoMonthStandardDeviationOfBalance?: unknown;
  /** Six month standard deviation of customer balance. */
  sixMonthStandardDeviationOfBalance?: unknown;
  /** Twelve month standard deviation of customer balance. */
  twelveMonthStandardDeviationOfBalance?: unknown;
}

export const consumerAttributesAssetsCustomerSchema: Schema<ConsumerAttributesAssetsCustomer> = object(
  {
    monthlyMinimumBalance: ['monthlyMinimumBalance', optional(unknown())],
    monthlyMaximumBalance: ['monthlyMaximumBalance', optional(unknown())],
    monthlyAverageBalance: ['monthlyAverageBalance', optional(unknown())],
    monthlyStandardDeviationOfBalance: [
      'monthlyStandardDeviationOfBalance',
      optional(unknown()),
    ],
    monthlyDaysWithPositiveBalance: [
      'monthlyDaysWithPositiveBalance',
      optional(unknown()),
    ],
    monthlyDaysWithNegativeBalance: [
      'monthlyDaysWithNegativeBalance',
      optional(unknown()),
    ],
    monthlyTwoMonthAverageBalance: [
      'monthlyTwoMonthAverageBalance',
      optional(unknown()),
    ],
    monthlySixMonthAverageBalance: [
      'monthlySixMonthAverageBalance',
      optional(unknown()),
    ],
    twelveMonthAverageBalance: [
      'twelveMonthAverageBalance',
      optional(unknown()),
    ],
    twoMonthStandardDeviationOfBalance: [
      'twoMonthStandardDeviationOfBalance',
      optional(unknown()),
    ],
    sixMonthStandardDeviationOfBalance: [
      'sixMonthStandardDeviationOfBalance',
      optional(unknown()),
    ],
    twelveMonthStandardDeviationOfBalance: [
      'twelveMonthStandardDeviationOfBalance',
      optional(unknown()),
    ],
  }
);
