/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface ConsumerAttributesDataLiabilities {
  /** Monthly loan deposits amount by account. */
  monthlyLoanDeposits?: unknown;
  /** Monthly loan withdrawal amount by account. */
  monthlyLoanWitdrawls?: unknown;
  /** Monthly count of the number of loan deposits by account. */
  monthlyNumberOfLoanDeposits?: unknown;
  /** Monthly amount of the number of loan deposits by account. */
  monthlyNumberOfLoanWithdrawls?: unknown;
}

export const consumerAttributesDataLiabilitiesSchema: Schema<ConsumerAttributesDataLiabilities> = object(
  {
    monthlyLoanDeposits: ['monthlyLoanDeposits', optional(unknown())],
    monthlyLoanWitdrawls: ['monthlyLoanWitdrawls', optional(unknown())],
    monthlyNumberOfLoanDeposits: [
      'monthlyNumberOfLoanDeposits',
      optional(unknown()),
    ],
    monthlyNumberOfLoanWithdrawls: [
      'monthlyNumberOfLoanWithdrawls',
      optional(unknown()),
    ],
  }
);
