/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** A list of account IDs */
export interface ConsumerAttributeAccountIDs {
  /** The list of account IDs */
  accountIds: string[];
}

export const consumerAttributeAccountIDsSchema: Schema<ConsumerAttributeAccountIDs> = object(
  { accountIds: ['accountIds', array(string())] }
);
