/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Birthday, birthdaySchema } from './birthday';

export interface ConsumerUpdate {
  /** First name(s) / given name(s) */
  firstName?: string;
  /** Last name(s) / surname(s) */
  lastName?: string;
  /** A street address */
  address?: string;
  /** A city */
  city?: string;
  /** A state */
  state?: string;
  /** A ZIP code */
  zip?: string;
  /** A phone number */
  phone?: string;
  /** A full SSN with or without hyphens */
  ssn?: string;
  /** A birth date */
  birthday?: Birthday;
  /** An email address */
  email?: string;
  /** A person suffix */
  suffix?: string;
}

export const consumerUpdateSchema: Schema<ConsumerUpdate> = object({
  firstName: ['firstName', optional(string())],
  lastName: ['lastName', optional(string())],
  address: ['address', optional(string())],
  city: ['city', optional(string())],
  state: ['state', optional(string())],
  zip: ['zip', optional(string())],
  phone: ['phone', optional(string())],
  ssn: ['ssn', optional(string())],
  birthday: ['birthday', optional(lazy(() => birthdaySchema))],
  email: ['email', optional(string())],
  suffix: ['suffix', optional(string())],
});
