/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { MonthlyNetAmount, monthlyNetAmountSchema } from './monthlyNetAmount';

export interface ConsumerAttributesDataNetAmount {
  /** Monthly net amount */
  monthlyNetAmount: MonthlyNetAmount;
}

export const consumerAttributesDataNetAmountSchema: Schema<ConsumerAttributesDataNetAmount> = object(
  { monthlyNetAmount: ['monthlyNetAmount', lazy(() => monthlyNetAmountSchema)] }
);
