/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  ConsumerAttributesData,
  consumerAttributesDataSchema,
} from './consumerAttributesData';

export interface ConsumerAttributes {
  /** An ID for a Consumer Attributes report */
  analyticsId: string;
  ca360Data: ConsumerAttributesData;
}

export const consumerAttributesSchema: Schema<ConsumerAttributes> = object({
  analyticsId: ['analytics_id', string()],
  ca360Data: ['ca360_data', lazy(() => consumerAttributesDataSchema)],
});
