/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, Schema } from '../schema';

/** Response for TxPush test transaction */
export interface CreatedTestTxPushTransaction {
  /** A Finicity transaction ID */
  id: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  createdDate: bigint;
}

export const createdTestTxPushTransactionSchema: Schema<CreatedTestTxPushTransaction> = object(
  { id: ['id', bigint()], createdDate: ['createdDate', bigint()] }
);
