/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

/** Details for investment account holdings */
export interface CustomerAccountPosition {
  /** The id of the investment position */
  id?: bigint;
  /** The description of the holding */
  description?: string;
  /** A nine-digit numeric or nine-character alphanumeric code that identifies a North American financial security (will be changed to SecurityIdType in the next API version, v2) */
  cusipNo?: string;
  /** Type of the security, attached Finicity's cusipNo field (will be changed to SecurityIdType in the next API version, v2) */
  cusipNoType?: string;
  /** The investment position's market/ticker symbol */
  symbol?: string;
  /** The quantity of investment holdings */
  units?: number;
  /** The current price of the investment holding */
  currentPrice?: number;
  /** The security name for the investment holding */
  securityName?: string;
  /** The transaction type of the holding. Cash, Margin, POSSTOCK, Etc */
  transactionType?: string;
  /** Market value of an investment position at the time of retrieval */
  marketValue?: number;
  /** The total cost of acquiring the security */
  costBasis?: number;
  /** The status of the holding */
  status?: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  currentPriceDate?: bigint;
  /** The investment holding security type */
  invSecurityType?: string;
  /** Type of mutual fund (e.g., open-ended) */
  mfType?: string;
  /** Fund Type assigned by the FI (long or short) */
  posType?: string;
  /** Total Gain/Loss of the position, at the time of aggregation ($) */
  totalGLDollar?: number;
  /** Total Gain/Loss of the position, at the time of aggregation (%) */
  totalGLPercent?: number;
}

export const customerAccountPositionSchema: Schema<CustomerAccountPosition> = object(
  {
    id: ['id', optional(bigint())],
    description: ['description', optional(string())],
    cusipNo: ['cusipNo', optional(string())],
    cusipNoType: ['cusipNoType', optional(string())],
    symbol: ['symbol', optional(string())],
    units: ['units', optional(number())],
    currentPrice: ['currentPrice', optional(number())],
    securityName: ['securityName', optional(string())],
    transactionType: ['transactionType', optional(string())],
    marketValue: ['marketValue', optional(number())],
    costBasis: ['costBasis', optional(number())],
    status: ['status', optional(string())],
    currentPriceDate: ['currentPriceDate', optional(bigint())],
    invSecurityType: ['invSecurityType', optional(string())],
    mfType: ['mfType', optional(string())],
    posType: ['posType', optional(string())],
    totalGLDollar: ['totalGLDollar', optional(number())],
    totalGLPercent: ['totalGLPercent', optional(number())],
  }
);
