/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Represent an update to customer fields */
export interface CustomerUpdate {
  /** First name(s) / given name(s) */
  firstName?: string;
  /** Last name(s) / surname(s) */
  lastName?: string;
}

export const customerUpdateSchema: Schema<CustomerUpdate> = object({
  firstName: ['firstName', optional(string())],
  lastName: ['lastName', optional(string())],
});
