/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

/** Additional customer account details. Not all data points will return for each account type. You can see the account type that each data point will return for in descriptions. The data point are also subject to availability by the institution. */
export interface CustomerAccountDetail {
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  postedDate?: bigint;
  /** (Checking/Savings/CD/MoneyMarket) and (Mortgage/Loan)  The available balance (typically the current balance with adjustments for any pending transactions) */
  availableBalanceAmount?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  openDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  periodStartDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  periodEndDate?: bigint;
  /** (Checking/Savings/CD/MoneyMarket) The APY for the current period interest rate */
  periodInterestRate?: number;
  /** (Checking/Savings/CD/MoneyMarket) Amount deposited in period */
  periodDepositAmount?: number;
  /** (Checking/Savings/CD/MoneyMarket) Interest accrued during the current period */
  periodInterestAmount?: number;
  /** (Checking/Savings/CD/MoneyMarket) Interest accrued year-to-date */
  interestYtdAmount?: number;
  /** (Checking/Savings/CD/MoneyMarket) Interest earned in prior year */
  interestPriorYtdAmount?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  maturityDate?: bigint;
  /** (Credit Card/Line Of Credit) and (Mortgage/Loan) The account's current interest rate */
  interestRate?: string;
  /** (Credit Card/Line Of Credit) The available credit (typically the credit limit minus the current balance) */
  creditAvailableAmount?: number;
  /** (Credit Card/Line Of Credit) The account's credit limit */
  creditMaxAmount?: number;
  /** (Credit Card/Line Of Credit) Currently available cash advance */
  cashAdvanceAvailableAmount?: number;
  /** (Credit Card/Line Of Credit) Maximum cash advance amount */
  cashAdvanceMaxAmount?: number;
  /** (Credit Card/Line Of Credit) Balance of current cash advance */
  cashAdvanceBalance?: number;
  /** (Credit Card/Line Of Credit) Interest rate for cash advances */
  cashAdvanceInterestRate?: number;
  /** (Credit Card/Line Of Credit) and (Investment) Current balance */
  currentBalance?: number;
  /** (Credit Card/Line Of Credit) and (Mortgage/Loan) Minimum payment due */
  paymentMinAmount?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  paymentDueDate?: bigint;
  /** (Credit Card/Line Of Credit) Prior balance in last statement */
  previousBalance?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  statementStartDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  statementEndDate?: bigint;
  /** (Credit Card/Line Of Credit) Purchase amount of statement period */
  statementPurchaseAmount?: number;
  /** (Credit Card/Line Of Credit) Finance amount of statement period */
  statementFinanceAmount?: number;
  /** (Credit Card/Line Of Credit) Credit amount applied in statement period */
  statementCreditAmount?: number;
  /** (Credit Card/Line Of Credit) Earned reward balance */
  rewardEarnedBalance?: number;
  /** (Credit Card/Line Of Credit) Balance past due */
  pastDueAmount?: number;
  /** (Credit Card/Line Of Credit) and (Mortgage/Loan) The amount received in the last payment */
  lastPaymentAmount?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  lastPaymentDate?: bigint;
  /** (Credit Card/Line Of Credit) Balance of statement at close */
  statementCloseBalance?: number;
  /** (Mortgage/Loan) Length of loan in months */
  termOfMl?: string;
  /** (Mortgage/Loan) Holder of the mortgage or loan */
  mlHolderName?: string;
  /** (Mortgage/Loan) Description of loan */
  description?: string;
  /** (Mortgage/Loan) Late fee charged */
  lateFeeAmount?: number;
  /** (Mortgage/Loan) The amount required to payoff the loan */
  payoffAmount?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  payoffAmountDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  originalMaturityDate?: bigint;
  /** (Mortgage/Loan) The principal balance */
  principalBalance?: number;
  /** (Mortgage/Loan) The escrow balance */
  escrowBalance?: number;
  /** (Mortgage/Loan) Period of interest */
  interestPeriod?: string;
  /** (Mortgage/Loan) Original loan amount */
  initialMlAmount?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  initialMlDate?: bigint;
  /** (Mortgage/Loan) Amount towards principal in next payment */
  nextPaymentPrincipalAmount?: number;
  /** (Mortgage/Loan) Amount of interest in next payment */
  nextPaymentInterestAmount?: number;
  /** (Mortgage/Loan) Minimum payment due */
  nextPayment?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  nextPaymentDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  lastPaymentDueDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  lastPaymentReceiveDate?: bigint;
  /** (Mortgage/Loan) Amount towards principal in last payment */
  lastPaymentPrincipalAmount?: number;
  /** (Mortgage/Loan) Amount of interest in last payment */
  lastPaymentInterestAmount?: number;
  /** (Mortgage/Loan) Amount towards escrow in last payment */
  lastPaymentEscrowAmount?: number;
  /** (Mortgage/Loan) Amount of last fee in last payment */
  lastPaymentLastFeeAmount?: number;
  /** (Mortgage/Loan) Amount of late charge in last payment */
  lastPaymentLateCharge?: number;
  /** (Mortgage/Loan) Principal paid year-to-date */
  ytdPrincipalPaid?: number;
  /** (Mortgage/Loan) Interest paid year-to-date */
  ytdInterestPaid?: number;
  /** (Mortgage/Loan) Insurance paid year-to-date */
  ytdInsurancePaid?: number;
  /** (Mortgage/Loan) Tax paid year-to-date */
  ytdTaxPaid?: number;
  /** (Mortgage/Loan) Enrolled in autopay (F/Y) */
  autoPayEnrolled?: string;
  /** (Mortgage/Loan) Collateral on loan */
  collateral?: string;
  /** (Mortgage/Loan) Current school */
  currentSchool?: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  firstPaymentDate?: bigint;
  /** (Mortgage/Loan) First mortgage (F/Y) */
  firstMortgage?: string;
  /** (Mortgage/Loan) Frequency of payments (monthly, etc.) */
  loanPaymentFreq?: string;
  /** (Mortgage/Loan) Original school */
  originalSchool?: string;
  /** (Mortgage/Loan) Recurring payment amount */
  recurringPaymentAmount?: number;
  /** (Mortgage/Loan) Owner of loan */
  lender?: string;
  /** (Mortgage/Loan) Ending balance */
  endingBalanceAmount?: number;
  /** (Mortgage/Loan) Type of loan term */
  loanTermType?: string;
  /** (Mortgage/Loan) Number of payments made */
  paymentsMade?: number;
  /** (Mortgage/Loan) Balloon payment amount */
  balloonAmount?: number;
  /** (Mortgage/Loan) Projected interest on the loan */
  projectedInterest?: number;
  /** (Mortgage/Loan) Interest paid since inception of loan (life to date) */
  interestPaidLtd?: number;
  /** (Mortgage/Loan) Type of interest rate */
  interestRateType?: string;
  /** (Mortgage/Loan) Type of loan payment */
  loanPaymentType?: string;
  /** (Mortgage/Loan) Type of repayment plan for the student loan */
  repaymentPlan?: string;
  /** (Mortgage/Loan) Number of payments remaining before loan is paid off */
  paymentsRemaining?: number;
  /** (Investment) Net interest earned after deducting interest paid out */
  interestMarginBalance?: number;
  /** (Investment) Sum of short balance */
  shortBalance?: number;
  /** (Investment) Amount available for cash withdrawal */
  availableCashBalance?: number;
  /** (Investment) amount payable to an investor at maturity */
  maturityValueAmount?: number;
  /** (Investment) Vested amount in account */
  vestedBalance?: number;
  /** (Investment) Employer matched contributions */
  empMatchAmount?: number;
  /** (Investment) Employer pretax contribution amount */
  empPretaxContribAmount?: number;
  /** (Investment) Employer pretax contribution amount year to date */
  empPretaxContribAmountYtd?: number;
  /** (Investment) Total year to date contributions */
  contribTotalYtd?: number;
  /** (Investment) Cash balance of account */
  cashBalanceAmount?: number;
  /** (Investment) Pre tax amount of total balance */
  preTaxAmount?: number;
  /** (Investment) Post tax amount of total balance */
  afterTaxAmount?: number;
  /** (Investment) Amount matched */
  matchAmount?: number;
  /** (Investment) Amount of balance for profit sharing */
  profitSharingAmount?: number;
  /** (Investment) Amount of balance rolled over from original account (401k, etc.) */
  rolloverAmount?: number;
  /** (Investment) Other vested amount */
  otherVestAmount?: number;
  /** (Investment) Other nonvested amount */
  otherNonvestAmount?: number;
  /** (Investment) Current loan balance */
  currentLoanBalance?: number;
  /** (Investment) Interest rate of loan */
  loanRate?: number;
  /** (Investment) Money available to buy securities */
  buyPower?: number;
  /** (Investment) Life to date of money rolled over */
  rolloverLtd?: number;
  /** (Student Loan) The federal unique loan identifying number */
  loanAwardId?: string;
  /** (Student Loan) The original interest rate to which the loan was disbursed, in APY */
  originalInterestRate?: number;
  /** (Student Loan) The financial institution guarantor of the loan (who will pay the loan amount to the owner if the borrower defaults) */
  guarantor?: string;
  /** (Student Loan) The indication of the presence of an interest subsidy (i.e. subsidized) */
  interestSubsityType?: string;
  /** (Student Loan) The total outstanding interest balance */
  interestBalance?: number;
  /** (Student Loan) The total outstanding fees balance */
  feesBalance?: number;
  /** (Student Loan) The repayment status phase (i.e. In School, Grace, Repayment, Deferment, Forbearance) */
  loanStatus?: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  loanStatusStartDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  loanStatusEndDate?: bigint;
  /** (Student Loan) The interest rate of multiple interest rates and balances at the group level, in APY */
  weightedInterestRate?: number;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  repaymentPlanStartDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  repaymentPlanEndDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  outOfSchoolDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  convertToRepayment?: bigint;
  /** (Student Loan) The number of days past a due date that a payment should have been made */
  daysDelinquent?: number;
  /** (Student Loan) The total amount paid towards the principal balance */
  totalPrincipalPaid?: number;
  /** (Student Loan) The total amount paid towards interest */
  totalInterestPaid?: number;
  /** (Student Loan) The total amount paid */
  totalAmountPaid?: number;
}

export const customerAccountDetailSchema: Schema<CustomerAccountDetail> = object(
  {
    postedDate: ['postedDate', optional(bigint())],
    availableBalanceAmount: ['availableBalanceAmount', optional(number())],
    openDate: ['openDate', optional(bigint())],
    periodStartDate: ['periodStartDate', optional(bigint())],
    periodEndDate: ['periodEndDate', optional(bigint())],
    periodInterestRate: ['periodInterestRate', optional(number())],
    periodDepositAmount: ['periodDepositAmount', optional(number())],
    periodInterestAmount: ['periodInterestAmount', optional(number())],
    interestYtdAmount: ['interestYtdAmount', optional(number())],
    interestPriorYtdAmount: ['interestPriorYtdAmount', optional(number())],
    maturityDate: ['maturityDate', optional(bigint())],
    interestRate: ['interestRate', optional(string())],
    creditAvailableAmount: ['creditAvailableAmount', optional(number())],
    creditMaxAmount: ['creditMaxAmount', optional(number())],
    cashAdvanceAvailableAmount: [
      'cashAdvanceAvailableAmount',
      optional(number()),
    ],
    cashAdvanceMaxAmount: ['cashAdvanceMaxAmount', optional(number())],
    cashAdvanceBalance: ['cashAdvanceBalance', optional(number())],
    cashAdvanceInterestRate: ['cashAdvanceInterestRate', optional(number())],
    currentBalance: ['currentBalance', optional(number())],
    paymentMinAmount: ['paymentMinAmount', optional(number())],
    paymentDueDate: ['paymentDueDate', optional(bigint())],
    previousBalance: ['previousBalance', optional(number())],
    statementStartDate: ['statementStartDate', optional(bigint())],
    statementEndDate: ['statementEndDate', optional(bigint())],
    statementPurchaseAmount: ['statementPurchaseAmount', optional(number())],
    statementFinanceAmount: ['statementFinanceAmount', optional(number())],
    statementCreditAmount: ['statementCreditAmount', optional(number())],
    rewardEarnedBalance: ['rewardEarnedBalance', optional(number())],
    pastDueAmount: ['pastDueAmount', optional(number())],
    lastPaymentAmount: ['lastPaymentAmount', optional(number())],
    lastPaymentDate: ['lastPaymentDate', optional(bigint())],
    statementCloseBalance: ['statementCloseBalance', optional(number())],
    termOfMl: ['termOfMl', optional(string())],
    mlHolderName: ['mlHolderName', optional(string())],
    description: ['description', optional(string())],
    lateFeeAmount: ['lateFeeAmount', optional(number())],
    payoffAmount: ['payoffAmount', optional(number())],
    payoffAmountDate: ['payoffAmountDate', optional(bigint())],
    originalMaturityDate: ['originalMaturityDate', optional(bigint())],
    principalBalance: ['principalBalance', optional(number())],
    escrowBalance: ['escrowBalance', optional(number())],
    interestPeriod: ['interestPeriod', optional(string())],
    initialMlAmount: ['initialMlAmount', optional(number())],
    initialMlDate: ['initialMlDate', optional(bigint())],
    nextPaymentPrincipalAmount: [
      'nextPaymentPrincipalAmount',
      optional(number()),
    ],
    nextPaymentInterestAmount: [
      'nextPaymentInterestAmount',
      optional(number()),
    ],
    nextPayment: ['nextPayment', optional(number())],
    nextPaymentDate: ['nextPaymentDate', optional(bigint())],
    lastPaymentDueDate: ['lastPaymentDueDate', optional(bigint())],
    lastPaymentReceiveDate: ['lastPaymentReceiveDate', optional(bigint())],
    lastPaymentPrincipalAmount: [
      'lastPaymentPrincipalAmount',
      optional(number()),
    ],
    lastPaymentInterestAmount: [
      'lastPaymentInterestAmount',
      optional(number()),
    ],
    lastPaymentEscrowAmount: ['lastPaymentEscrowAmount', optional(number())],
    lastPaymentLastFeeAmount: ['lastPaymentLastFeeAmount', optional(number())],
    lastPaymentLateCharge: ['lastPaymentLateCharge', optional(number())],
    ytdPrincipalPaid: ['ytdPrincipalPaid', optional(number())],
    ytdInterestPaid: ['ytdInterestPaid', optional(number())],
    ytdInsurancePaid: ['ytdInsurancePaid', optional(number())],
    ytdTaxPaid: ['ytdTaxPaid', optional(number())],
    autoPayEnrolled: ['autoPayEnrolled', optional(string())],
    collateral: ['collateral', optional(string())],
    currentSchool: ['currentSchool', optional(string())],
    firstPaymentDate: ['firstPaymentDate', optional(bigint())],
    firstMortgage: ['firstMortgage', optional(string())],
    loanPaymentFreq: ['loanPaymentFreq', optional(string())],
    originalSchool: ['originalSchool', optional(string())],
    recurringPaymentAmount: ['recurringPaymentAmount', optional(number())],
    lender: ['lender', optional(string())],
    endingBalanceAmount: ['endingBalanceAmount', optional(number())],
    loanTermType: ['loanTermType', optional(string())],
    paymentsMade: ['paymentsMade', optional(number())],
    balloonAmount: ['balloonAmount', optional(number())],
    projectedInterest: ['projectedInterest', optional(number())],
    interestPaidLtd: ['interestPaidLtd', optional(number())],
    interestRateType: ['interestRateType', optional(string())],
    loanPaymentType: ['loanPaymentType', optional(string())],
    repaymentPlan: ['repaymentPlan', optional(string())],
    paymentsRemaining: ['paymentsRemaining', optional(number())],
    interestMarginBalance: ['interestMarginBalance', optional(number())],
    shortBalance: ['shortBalance', optional(number())],
    availableCashBalance: ['availableCashBalance', optional(number())],
    maturityValueAmount: ['maturityValueAmount', optional(number())],
    vestedBalance: ['vestedBalance', optional(number())],
    empMatchAmount: ['empMatchAmount', optional(number())],
    empPretaxContribAmount: ['empPretaxContribAmount', optional(number())],
    empPretaxContribAmountYtd: [
      'empPretaxContribAmountYtd',
      optional(number()),
    ],
    contribTotalYtd: ['contribTotalYtd', optional(number())],
    cashBalanceAmount: ['cashBalanceAmount', optional(number())],
    preTaxAmount: ['preTaxAmount', optional(number())],
    afterTaxAmount: ['afterTaxAmount', optional(number())],
    matchAmount: ['matchAmount', optional(number())],
    profitSharingAmount: ['profitSharingAmount', optional(number())],
    rolloverAmount: ['rolloverAmount', optional(number())],
    otherVestAmount: ['otherVestAmount', optional(number())],
    otherNonvestAmount: ['otherNonvestAmount', optional(number())],
    currentLoanBalance: ['currentLoanBalance', optional(number())],
    loanRate: ['loanRate', optional(number())],
    buyPower: ['buyPower', optional(number())],
    rolloverLtd: ['rolloverLtd', optional(number())],
    loanAwardId: ['loanAwardId', optional(string())],
    originalInterestRate: ['originalInterestRate', optional(number())],
    guarantor: ['guarantor', optional(string())],
    interestSubsityType: ['interestSubsityType', optional(string())],
    interestBalance: ['interestBalance', optional(number())],
    feesBalance: ['feesBalance', optional(number())],
    loanStatus: ['loanStatus', optional(string())],
    loanStatusStartDate: ['loanStatusStartDate', optional(bigint())],
    loanStatusEndDate: ['loanStatusEndDate', optional(bigint())],
    weightedInterestRate: ['weightedInterestRate', optional(number())],
    repaymentPlanStartDate: ['repaymentPlanStartDate', optional(bigint())],
    repaymentPlanEndDate: ['repaymentPlanEndDate', optional(bigint())],
    outOfSchoolDate: ['outOfSchoolDate', optional(bigint())],
    convertToRepayment: ['convertToRepayment', optional(bigint())],
    daysDelinquent: ['daysDelinquent', optional(number())],
    totalPrincipalPaid: ['totalPrincipalPaid', optional(number())],
    totalInterestPaid: ['totalInterestPaid', optional(number())],
    totalAmountPaid: ['totalAmountPaid', optional(number())],
  }
);
