/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { CustomerAccount, customerAccountSchema } from './customerAccount';

/** A list of customer accounts */
export interface CustomerAccounts {
  /** List of customer accounts */
  accounts: CustomerAccount[];
}

export const customerAccountsSchema: Schema<CustomerAccounts> = object({
  accounts: ['accounts', array(lazy(() => customerAccountSchema))],
});
