/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, number, object, Schema } from '../schema';
import { Customer, customerSchema } from './customer';

/** A list of Finicity customers */
export interface Customers {
  /** The total number of results matching search criteria */
  found: number;
  /** The number of results returned */
  displaying: number;
  /** If `true`, you can fetch the next page of results */
  moreAvailable: boolean;
  /** A list of customer records */
  customers: Customer[];
}

export const customersSchema: Schema<Customers> = object({
  found: ['found', number()],
  displaying: ['displaying', number()],
  moreAvailable: ['moreAvailable', boolean()],
  customers: ['customers', array(lazy(() => customerSchema))],
});
