/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum';
import {
  CustomerAccountDetail,
  customerAccountDetailSchema,
} from './customerAccountDetail';
import {
  CustomerAccountPosition,
  customerAccountPositionSchema,
} from './customerAccountPosition';

/** An account represents a bank account such as a checking or savings that the customer has added via the Connect interface. */
export interface CustomerAccount {
  /** A Finicity account ID */
  id: string;
  /** Use `accountNumberDisplay` field. Starting July 1, 2021 the `number` field will sunset with limited support until April 1, 2022, at which time it will be deprecated (no longer available). */
  number: string;
  /**
   * The account number from a financial institution in truncated format:
   * * Last four digits: "1234"
   * * Last four digits with suffix: "1234-9"
   * * Full value for string accounts: "john@gmail.com"
   */
  accountNumberDisplay: string;
  /** The last 4 digits of the ACH account number */
  realAccountNumberLast4?: string;
  /** The account name from the institution */
  name: string;
  /** The cleared balance of the account as-of balanceDate */
  balance: number;
  /**
   * The enumeration of supported account types.
   * * `checking`: Standard checking
   * * `savings`: Standard savings
   * * `cd`: Certificates of deposit
   * * `moneyMarket`: Money Market
   * * `creditCard`: Standard credit cards
   * * `lineOfCredit`: Home equity, line of credit
   * * `investment`: Generic investment (no details)
   * * `investmentTaxDeferred`: Generic tax-advantaged investment (no details)
   * * `employeeStockPurchasePlan`: ESPP, Employee Stock Ownership Plans (ESOP), Stock Purchase Plans
   * * `ira`: Individual Retirement Account (not Rollover or Roth)
   * * `401k`: 401K Plan
   * * `roth`: Roth IRA, Roth 401K
   * * `403b`: 403B Plan
   * * `529plan`: 529 Plan (True value is 529)
   * * `rollover`: Rollover IRA
   * * `ugma`: Uniform Gifts to Minors Act
   * * `utma`: Uniform Transfers to Minors Act
   * * `keogh`: Keogh Plan
   * * `457plan`: 457 Plan (True value is 457)
   * * `401a`: 401A Plan
   * * `mortgage`: Standard Mortgages
   * * `loan`: Auto loans, equity loans, other loans
   * * `studentLoan`: Student Loan
   * * `studentLoanGroup`: Student Loan Group
   * * `studentLoanAccount`: Student Loan Account
   */
  type: AccountTypeEnum;
  /** The status of the most recent aggregation attempt (see [Aggregation Status Codes](https://docs.finicity.com/aggregation-status-codes/)). Won't be present until you have run your first aggregation for the account. */
  aggregationStatusCode?: number;
  /** "pending" during account discovery, always "active" following successful account activation */
  status: string;
  /** A Finicity customer ID. See also: "Add Customer". */
  customerId: string;
  /** The ID of a financial institution */
  institutionId: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  balanceDate: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  aggregationSuccessDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  aggregationAttemptDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  createdDate: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  lastUpdatedDate?: bigint;
  /** A currency code */
  currency: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  lastTransactionDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  oldestTransactionDate?: bigint;
  /** An institution login ID (from the account record), represented as a number */
  institutionLoginId: bigint;
  /** Additional customer account details. Not all data points will return for each account type. You can see the account type that each data point will return for in descriptions. The data point are also subject to availability by the institution. */
  detail?: CustomerAccountDetail;
  /** Investment holdings */
  position?: CustomerAccountPosition[];
  /** Display position of the account at the financial institution, "1" being the top listed account */
  displayPosition: number;
  /** A Finicity account ID */
  parentAccount?: string;
  /** Current account status with the financial institution */
  financialinstitutionAccountStatus?: string;
  /** Nickname for account */
  accountNickname?: string;
  /** Market segment of account */
  marketSegment?: string;
}

export const customerAccountSchema: Schema<CustomerAccount> = object({
  id: ['id', string()],
  number: ['number', string()],
  accountNumberDisplay: ['accountNumberDisplay', string()],
  realAccountNumberLast4: ['realAccountNumberLast4', optional(string())],
  name: ['name', string()],
  balance: ['balance', number()],
  type: ['type', accountTypeEnumSchema],
  aggregationStatusCode: ['aggregationStatusCode', optional(number())],
  status: ['status', string()],
  customerId: ['customerId', string()],
  institutionId: ['institutionId', string()],
  balanceDate: ['balanceDate', bigint()],
  aggregationSuccessDate: ['aggregationSuccessDate', optional(bigint())],
  aggregationAttemptDate: ['aggregationAttemptDate', optional(bigint())],
  createdDate: ['createdDate', bigint()],
  lastUpdatedDate: ['lastUpdatedDate', optional(bigint())],
  currency: ['currency', string()],
  lastTransactionDate: ['lastTransactionDate', optional(bigint())],
  oldestTransactionDate: ['oldestTransactionDate', optional(bigint())],
  institutionLoginId: ['institutionLoginId', bigint()],
  detail: ['detail', optional(lazy(() => customerAccountDetailSchema))],
  position: [
    'position',
    optional(array(lazy(() => customerAccountPositionSchema))),
  ],
  displayPosition: ['displayPosition', number()],
  parentAccount: ['parentAccount', optional(string())],
  financialinstitutionAccountStatus: [
    'financialinstitutionAccountStatus',
    optional(string()),
  ],
  accountNickname: ['accountNickname', optional(string())],
  marketSegment: ['marketSegment', optional(string())],
});
