/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** A finicity customer record with application info */
export interface CustomerWithAppData {
  /** A Finicity customer ID. See also: "Add Customer". */
  id: string;
  /** The customer's username, assigned by the partner (a unique identifier), following these rules: minimum 6 characters maximum 255 characters any mix of uppercase, lowercase, numeric, and non-alphabet special characters ! @ . # $ % & * _ – + the use of email in this field is discouraged it is recommended to use a unique non-email identifier. Use of special characters may result in an error (e.g. í, ü, etc.) */
  username: string;
  /** First name(s) / given name(s) */
  firstName: string;
  /** Last name(s) / surname(s) */
  lastName: string;
  /** The type of Finicity customer ("active" or "testing" or "" for all types) */
  type: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  createdDate: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  lastModifiedDate?: string;
  /** `applicationId` value returned from the "Get App Registration Status" endpoint and the partner assign the customers to. This cannot be changed once set. Only applicable in cases of partners with multiple registered applications. If the partner only has one app, this can usually be omitted. This field is populated after the app is in a status approved. */
  applicationId: string;
  /** The name of the application assigned to the customer */
  applicationName: string;
}

export const customerWithAppDataSchema: Schema<CustomerWithAppData> = object({
  id: ['id', string()],
  username: ['username', string()],
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  type: ['type', string()],
  createdDate: ['createdDate', string()],
  lastModifiedDate: ['lastModifiedDate', optional(string())],
  applicationId: ['applicationId', string()],
  applicationName: ['applicationName', string()],
});
