/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** Configuration for the Connect email's sent to customers */
export interface EmailOptions {
  /** The email address for the customer receiving the Connect email */
  to: string;
  /** The name of a person or business sending the Connect email */
  from?: string;
  /** The support phone number listed in the email */
  supportPhone?: string;
  /** The subject line of the email. The default is "Verify your Financial Information". */
  subject?: string;
  /** The first name of the customer or both names of the customers for joint borrowers. Example: "Marvin and Jenny". */
  firstName?: string;
  /** The name of your company */
  institutionName?: string;
  /** The institution address to appear in the footer of the email */
  institutionAddress?: string;
  /** A signature for the email */
  signature?: string[];
}

export const emailOptionsSchema: Schema<EmailOptions> = object({
  to: ['to', string()],
  from: ['from', optional(string())],
  supportPhone: ['supportPhone', optional(string())],
  subject: ['subject', optional(string())],
  firstName: ['firstName', optional(string())],
  institutionName: ['institutionName', optional(string())],
  institutionAddress: ['institutionAddress', optional(string())],
  signature: ['signature', optional(array(string()))],
});
