/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The address of a financial institution */
export interface InstitutionAddress {
  /** A city */
  city?: string;
  /** A state */
  state?: string;
  /** A country code */
  country?: string;
  /** A ZIP code */
  postalCode?: string;
  /** An address line 1 */
  addressLine1?: string;
  /** An address line 2 */
  addressLine2?: string;
}

export const institutionAddressSchema: Schema<InstitutionAddress> = object({
  city: ['city', optional(string())],
  state: ['state', optional(string())],
  country: ['country', optional(string())],
  postalCode: ['postalCode', optional(string())],
  addressLine1: ['addressLine1', optional(string())],
  addressLine2: ['addressLine2', optional(string())],
});
