/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Institution, institutionSchema } from './institution';

export interface InstitutionWrapper {
  /** A financial institution */
  institution: Institution;
}

export const institutionWrapperSchema: Schema<InstitutionWrapper> = object({
  institution: ['institution', lazy(() => institutionSchema)],
});
