/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  LoanPaymentDetailsAccount,
  loanPaymentDetailsAccountSchema,
} from './loanPaymentDetailsAccount';

/** Loan payment details for a customer account */
export interface LoanPaymentDetails {
  /** The number of the specific loan under the account. */
  loanNumber: string;
  /** The payment number given by the institution. This number is typically for manual payments. This is not an ACH payment number. */
  loanPaymentNumber: string;
  /** The payment address to send manual payments to */
  loanPaymentAddress: string;
  accountDetail?: LoanPaymentDetailsAccount;
}

export const loanPaymentDetailsSchema: Schema<LoanPaymentDetails> = object({
  loanNumber: ['loanNumber', string()],
  loanPaymentNumber: ['loanPaymentNumber', string()],
  loanPaymentAddress: ['loanPaymentAddress', string()],
  accountDetail: [
    'accountDetail',
    optional(lazy(() => loanPaymentDetailsAccountSchema)),
  ],
});
