/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  LoanPaymentDetailsGroup,
  loanPaymentDetailsGroupSchema,
} from './loanPaymentDetailsGroup';
import {
  LoanPaymentDetailsLoan,
  loanPaymentDetailsLoanSchema,
} from './loanPaymentDetailsLoan';

export interface LoanPaymentDetailsAccount {
  /** A Finicity account ID */
  accountId: string;
  /** Institution's ID of the Student Loan Account */
  accountNumber: string;
  /** The payment number given by the institution. This number is typically for manual payments. This is not an ACH payment number. */
  accountPaymentNumber: string;
  /** The payment address to which send manual payments should be sent */
  accountPaymentAddress: string;
  /** The payoff amount for the account */
  accountFuturePayoffAmount?: number;
  /** The date to which the "Future Payoff Amount" applies */
  accountFuturePayoffDate?: string;
  /** Group details */
  groupDetail?: LoanPaymentDetailsGroup[];
  /** Loan details */
  loanDetail?: LoanPaymentDetailsLoan[];
}

export const loanPaymentDetailsAccountSchema: Schema<LoanPaymentDetailsAccount> = object(
  {
    accountId: ['accountId', string()],
    accountNumber: ['accountNumber', string()],
    accountPaymentNumber: ['accountPaymentNumber', string()],
    accountPaymentAddress: ['accountPaymentAddress', string()],
    accountFuturePayoffAmount: [
      'accountFuturePayoffAmount',
      optional(number()),
    ],
    accountFuturePayoffDate: ['accountFuturePayoffDate', optional(string())],
    groupDetail: [
      'groupDetail',
      optional(array(lazy(() => loanPaymentDetailsGroupSchema))),
    ],
    loanDetail: [
      'loanDetail',
      optional(array(lazy(() => loanPaymentDetailsLoanSchema))),
    ],
  }
);
