/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

/** Monthly net amount */
export interface MonthlyNetAmount {
  /** Net amount per month */
  netAmount?: unknown;
}

export const monthlyNetAmountSchema: Schema<MonthlyNetAmount> = object({
  netAmount: ['NetAmount', optional(unknown())],
});
