/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** A new customer to be enrolled */
export interface NewCustomer {
  /** The customer's username, assigned by the partner (a unique identifier), following these rules: minimum 6 characters maximum 255 characters any mix of uppercase, lowercase, numeric, and non-alphabet special characters ! @ . # $ % & * _ – + the use of email in this field is discouraged it is recommended to use a unique non-email identifier. Use of special characters may result in an error (e.g. í, ü, etc.) */
  username: string;
  /** First name(s) / given name(s) */
  firstName?: string;
  /** Last name(s) / surname(s) */
  lastName?: string;
  /** `applicationId` value returned from the "Get App Registration Status" endpoint and the partner assign the customers to. This cannot be changed once set. Only applicable in cases of partners with multiple registered applications. If the partner only has one app, this can usually be omitted. This field is populated after the app is in a status approved. */
  applicationId?: string;
}

export const newCustomerSchema: Schema<NewCustomer> = object({
  username: ['username', string()],
  firstName: ['firstName', optional(string())],
  lastName: ['lastName', optional(string())],
  applicationId: ['applicationId', optional(string())],
});
