/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Birthday, birthdaySchema } from './birthday';

/** A new consumer to be created */
export interface NewConsumer {
  /** First name(s) / given name(s) */
  firstName: string;
  /** Last name(s) / surname(s) */
  lastName: string;
  /** A street address */
  address: string;
  /** A city */
  city: string;
  /** A state */
  state: string;
  /** A ZIP code */
  zip: string;
  /** A phone number */
  phone: string;
  /** A full SSN with or without hyphens */
  ssn: string;
  /** A birth date */
  birthday: Birthday;
  /** An email address */
  email?: string;
  /** A person suffix */
  suffix?: string;
}

export const newConsumerSchema: Schema<NewConsumer> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  address: ['address', string()],
  city: ['city', string()],
  state: ['state', string()],
  zip: ['zip', string()],
  phone: ['phone', string()],
  ssn: ['ssn', string()],
  birthday: ['birthday', lazy(() => birthdaySchema)],
  email: ['email', optional(string())],
  suffix: ['suffix', optional(string())],
});
