/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PartnerCredentials {
  /** Your Partner ID displayed in the [Developer Dashboard](https://developer.finicity.com/admin) */
  partnerId: string;
  /** Your Partner Secret displayed in the [Developer Dashboard](https://developer.finicity.com/admin) */
  partnerSecret: string;
}

export const partnerCredentialsSchema: Schema<PartnerCredentials> = object({
  partnerId: ['partnerId', string()],
  partnerSecret: ['partnerSecret', string()],
});
