/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PartnerCredentialsWithNewSecret {
  /** Your Partner ID displayed in the [Developer Dashboard](https://developer.finicity.com/admin) */
  partnerId: string;
  /** Your Partner Secret displayed in the [Developer Dashboard](https://developer.finicity.com/admin) */
  partnerSecret: string;
  /** A new value for the Partner Secret */
  newPartnerSecret: string;
}

export const partnerCredentialsWithNewSecretSchema: Schema<PartnerCredentialsWithNewSecret> = object(
  {
    partnerId: ['partnerId', string()],
    partnerSecret: ['partnerSecret', string()],
    newPartnerSecret: ['newPartnerSecret', string()],
  }
);
