/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface PayrollDataOut {
  /** An id to identify the data retrieved from the payroll providers for the report. */
  payrollDataRetrievalId: string;
  /** An array of employer names that the consumer submitted after completing the Connect application. */
  employerNames: string[];
  /** A Finicity report ID */
  reportId?: string;
}

export const payrollDataOutSchema: Schema<PayrollDataOut> = object({
  payrollDataRetrievalId: ['payrollDataRetrievalId', string()],
  employerNames: ['employerNames', array(string())],
  reportId: ['reportId', optional(string())],
});
