/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, Schema, string } from '../schema';
import { ReportTypeEnum, reportTypeEnumSchema } from './reportTypeEnum';

export interface PortfolioReport {
  /** A Finicity report ID */
  id: string;
  /** A unique identifier that will be consistent across all reports created for the same customer */
  portfolioId: string;
  type: ReportTypeEnum;
  /** A report generation status ("inProgress", "success", "failure") */
  status: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  createdDate: bigint;
}

export const portfolioReportSchema: Schema<PortfolioReport> = object({
  id: ['id', string()],
  portfolioId: ['portfolioId', string()],
  type: ['type', reportTypeEnumSchema],
  status: ['status', string()],
  createdDate: ['createdDate', bigint()],
});
