/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { PortfolioConsumer, portfolioConsumerSchema } from './portfolioConsumer';
import { PortfolioReport, portfolioReportSchema } from './portfolioReport';

export interface PortfolioWithConsumerSummary {
  /** A unique identifier that will be consistent across all reports created for the same customer */
  portfolioId: string;
  /** A list of reports in the portfolio */
  reports: PortfolioReport[];
  consumer: PortfolioConsumer;
}

export const portfolioWithConsumerSummarySchema: Schema<PortfolioWithConsumerSummary> = object(
  {
    portfolioId: ['portfolioId', string()],
    reports: ['reports', array(lazy(() => portfolioReportSchema))],
    consumer: ['consumer', lazy(() => portfolioConsumerSchema)],
  }
);
