/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, object, optional, Schema, string } from '../schema';
import { Birthday, birthdaySchema } from './birthday';

export interface PortfolioConsumer {
  /** A Finicity consumer ID. See also: "Create Consumer". */
  id: string;
  /** First name(s) / given name(s) */
  firstName: string;
  /** Last name(s) / surname(s) */
  lastName: string;
  /** A Finicity customer ID represented as a number. See also: "Add Customer". */
  customerId: bigint;
  /** A full SSN with or without hyphens */
  ssn: string;
  /** A birth date */
  birthday: Birthday;
  /** A person suffix */
  suffix?: string;
}

export const portfolioConsumerSchema: Schema<PortfolioConsumer> = object({
  id: ['id', string()],
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  customerId: ['customerId', bigint()],
  ssn: ['ssn', string()],
  birthday: ['birthday', lazy(() => birthdaySchema)],
  suffix: ['suffix', optional(string())],
});
