/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ErrorMessage, errorMessageSchema } from './errorMessage';
import {
  PrequalificationReportAssetSummary,
  prequalificationReportAssetSummarySchema,
} from './prequalificationReportAssetSummary';
import {
  ReportConstraintsOut,
  reportConstraintsOutSchema,
} from './reportConstraintsOut';
import { ReportInstitution, reportInstitutionSchema } from './reportInstitution';
import { ReportTypeEnum, reportTypeEnumSchema } from './reportTypeEnum';

/** A Prequalification report */
export interface PrequalificationReport {
  /** A Finicity report ID */
  id: string;
  /** A Finicity customer ID represented as a number. See also: "Add Customer". */
  customerId: bigint;
  /** A Finicity consumer ID. See also: "Create Consumer". */
  consumerId?: string;
  /** Last 4 digits of a SSN */
  consumerSsn?: string;
  /** Name of a Finicity partner */
  requesterName: string;
  /** Finicity indicator to track all activity associated with this report */
  requestId: string;
  type: ReportTypeEnum;
  /** A report generation status ("inProgress", "success", "failure") */
  status: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  createdDate: bigint;
  constraints: ReportConstraintsOut;
  /** The type of Finicity customer ("active" or "testing" or "" for all types) */
  customerType: string;
  /** Title of the report */
  title: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  startDate: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  endDate: bigint;
  /** Number of days covered by the report */
  days: number;
  /** If a report covers more than 180 days */
  seasoned: boolean;
  /** A unique identifier that will be consistent across all reports created for the same customer */
  portfolioId: string;
  /** Sum of available balances for all of the accounts included in the report */
  consolidatedAvailableBalance: number;
  /** A list of institution records, including information about the individual accounts used in this report */
  institutions: ReportInstitution[];
  /** In case errors occurred during the report generation */
  errors?: ErrorMessage[];
  assets: PrequalificationReportAssetSummary;
}

export const prequalificationReportSchema: Schema<PrequalificationReport> = object(
  {
    id: ['id', string()],
    customerId: ['customerId', bigint()],
    consumerId: ['consumerId', optional(string())],
    consumerSsn: ['consumerSsn', optional(string())],
    requesterName: ['requesterName', string()],
    requestId: ['requestId', string()],
    type: ['type', reportTypeEnumSchema],
    status: ['status', string()],
    createdDate: ['createdDate', bigint()],
    constraints: ['constraints', lazy(() => reportConstraintsOutSchema)],
    customerType: ['customerType', string()],
    title: ['title', string()],
    startDate: ['startDate', bigint()],
    endDate: ['endDate', bigint()],
    days: ['days', number()],
    seasoned: ['seasoned', boolean()],
    portfolioId: ['portfolioId', string()],
    consolidatedAvailableBalance: ['consolidatedAvailableBalance', number()],
    institutions: ['institutions', array(lazy(() => reportInstitutionSchema))],
    errors: ['errors', optional(array(lazy(() => errorMessageSchema)))],
    assets: ['assets', lazy(() => prequalificationReportAssetSummarySchema)],
  }
);
