/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { ReportSummary, reportSummarySchema } from './reportSummary';

export interface ReportSummaries {
  /** Data pertaining to each report */
  reports: ReportSummary[];
}

export const reportSummariesSchema: Schema<ReportSummaries> = object({
  reports: ['reports', array(lazy(() => reportSummarySchema))],
});
