/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReportTypeEnum
 */
export enum ReportTypeEnum {
  Voi = 'voi',
  Voa = 'voa',
  VoaHistory = 'voaHistory',
  History = 'history',
  VoieTxVerify = 'voieTxVerify',
  VoieWithReport = 'voieWithReport',
  VoieWithInterview = 'voieWithInterview',
  Paystatement = 'paystatement',
  PreQualVoa = 'preQualVoa',
  AssetSummary = 'assetSummary',
  VoieWithStatement = 'voieWithStatement',
  Transactions = 'transactions',
  Statement = 'statement',
  VoiePayroll = 'voiePayroll',
  VoeTransactions = 'voeTransactions',
  VoePayroll = 'voePayroll',
  Cfrp = 'cfrp',
  Cfrb = 'cfrb',
}

/**
 * Schema for ReportTypeEnum
 */
export const reportTypeEnumSchema: Schema<ReportTypeEnum> = stringEnum(ReportTypeEnum);
