/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, Schema, string } from '../schema';
import { ReportAccount, reportAccountSchema } from './reportAccount';

export interface ReportInstitution {
  /** The ID of a financial institution, represented as a number */
  id: bigint;
  /** The name of the institution */
  name: string;
  /** The URL of the institution's primary home page */
  urlHomeApp: string;
  /** An array of accounts */
  accounts: ReportAccount[];
}

export const reportInstitutionSchema: Schema<ReportInstitution> = object({
  id: ['id', bigint()],
  name: ['name', string()],
  urlHomeApp: ['urlHomeApp', string()],
  accounts: ['accounts', array(lazy(() => reportAccountSchema))],
});
