/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReportTransactionPayStatementMatchTypesEnum
 */
export enum ReportTransactionPayStatementMatchTypesEnum {
  DATE = 'DATE',
  NETAMOUNT = 'NET_AMOUNT',
  INTERVIEWAMOUNT = 'INTERVIEW_AMOUNT',
  LESSTHANNETPAY = 'LESS_THAN_NET_PAY',
  EMPLOYERNAME = 'EMPLOYER_NAME',
  INCOMESTREAMPAYCHECK = 'INCOME_STREAM_PAYCHECK',
  DIRECTDEPOSITAMOUNT = 'DIRECT_DEPOSIT_AMOUNT',
  PAYROLLPROVIDER = 'PAYROLL_PROVIDER',
}

/**
 * Schema for ReportTransactionPayStatementMatchTypesEnum
 */
export const reportTransactionPayStatementMatchTypesEnumSchema: Schema<ReportTransactionPayStatementMatchTypesEnum> = stringEnum(ReportTransactionPayStatementMatchTypesEnum);
