/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ReportCustomField, reportCustomFieldSchema } from './reportCustomField';
import { StatementData, statementDataSchema } from './statementData';

export interface StatementReportConstraints {
  statementReportData: StatementData;
  /**
   * The `reportCustomFields` parameter is used when experiences are associated with a credit decisioning report.
   * Designate up to 5 custom fields that you'd like associated with the report when it's generated. Every custom field consists of three variables: `label`, `value`, and `shown`. The `shown` variable is true or false.
   * * `true`: (default) display the custom field in the PDF report
   * * `false`: don't display the custom field in the PDF report
   * For an experience that generates multiple reports, the `reportCustomFields` parameter gets passed to all reports.
   * All custom fields display in the Reseller Billing endpoint.
   */
  reportCustomFields?: ReportCustomField[];
}

export const statementReportConstraintsSchema: Schema<StatementReportConstraints> = object(
  {
    statementReportData: [
      'statementReportData',
      lazy(() => statementDataSchema),
    ],
    reportCustomFields: [
      'reportCustomFields',
      optional(array(lazy(() => reportCustomFieldSchema))),
    ],
  }
);
