/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema } from '../schema';

export interface StatementData {
  /** A Finicity account ID represented as a number */
  accountId: bigint;
  /** Index of the statement to retrieve */
  index?: number;
}

export const statementDataSchema: Schema<StatementData> = object({
  accountId: ['accountId', bigint()],
  index: ['index', optional(number())],
});
