/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, Schema, string } from '../schema';

/** TxPush subscription details */
export interface SubscriptionRecord {
  /** ID of a TxPush subscription */
  id: bigint;
  /** A Finicity account ID represented as a number */
  accountId: bigint;
  /** A TxPush subscription type ("account" or "transaction") */
  type: string;
  /** A callback URL where to receive TxPush notifications */
  callbackUrl: string;
  /** Signing key for events */
  signingKey: string;
}

export const subscriptionRecordSchema: Schema<SubscriptionRecord> = object({
  id: ['id', bigint()],
  accountId: ['accountId', bigint()],
  type: ['type', string()],
  callbackUrl: ['callbackUrl', string()],
  signingKey: ['signingKey', string()],
});
