/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

/** A fake transaction for TxPush testing */
export interface TestTxPushTransaction {
  /** The amount of the transaction */
  amount: number;
  /** The description of the transaction */
  description: string;
  /** active or pending (optional) */
  status?: string;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  postedDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  transactionDate: bigint;
}

export const testTxPushTransactionSchema: Schema<TestTxPushTransaction> = object(
  {
    amount: ['amount', number()],
    description: ['description', string()],
    status: ['status', optional(string())],
    postedDate: ['postedDate', optional(bigint())],
    transactionDate: ['transactionDate', bigint()],
  }
);
