/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionTypeEnum
 */
export enum TransactionTypeEnum {
  Atm = 'atm',
  Cash = 'cash',
  Check = 'check',
  Credit = 'credit',
  Debit = 'debit',
  Deposit = 'deposit',
  DirectDebit = 'directDebit',
  DirectDeposit = 'directDeposit',
  Dividend = 'dividend',
  Fee = 'fee',
  Interest = 'interest',
  Other = 'other',
  Payment = 'payment',
  PointOfSale = 'pointOfSale',
  RepeatPayment = 'repeatPayment',
  ServiceCharge = 'serviceCharge',
  Transfer = 'transfer',
}

/**
 * Schema for TransactionTypeEnum
 */
export const transactionTypeEnumSchema: Schema<TransactionTypeEnum> = stringEnum(TransactionTypeEnum);
