/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ReportCustomField, reportCustomFieldSchema } from './reportCustomField';

export interface TransactionReportConstraints {
  /** An array of Finicity account IDs to be included in the report (all accounts will be included if not set) */
  accountIds?: string[];
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  fromDate?: bigint;
  /** A date in Unix epoch time (in seconds). See also: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/). */
  toDate?: bigint;
  /** If pending transactions must be included */
  includePending?: boolean;
  /**
   * The `reportCustomFields` parameter is used when experiences are associated with a credit decisioning report.
   * Designate up to 5 custom fields that you'd like associated with the report when it's generated. Every custom field consists of three variables: `label`, `value`, and `shown`. The `shown` variable is true or false.
   * * `true`: (default) display the custom field in the PDF report
   * * `false`: don't display the custom field in the PDF report
   * For an experience that generates multiple reports, the `reportCustomFields` parameter gets passed to all reports.
   * All custom fields display in the Reseller Billing endpoint.
   */
  reportCustomFields?: ReportCustomField[];
}

export const transactionReportConstraintsSchema: Schema<TransactionReportConstraints> = object(
  {
    accountIds: ['accountIds', optional(array(string()))],
    fromDate: ['fromDate', optional(bigint())],
    toDate: ['toDate', optional(bigint())],
    includePending: ['includePending', optional(boolean())],
    reportCustomFields: [
      'reportCustomFields',
      optional(array(lazy(() => reportCustomFieldSchema))),
    ],
  }
);
