/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  SubscriptionRecord,
  subscriptionRecordSchema,
} from './subscriptionRecord';

export interface TxPushSubscriptions {
  subscriptions: SubscriptionRecord[];
}

export const txPushSubscriptionsSchema: Schema<TxPushSubscriptions> = object({
  subscriptions: ['subscriptions', array(lazy(() => subscriptionRecordSchema))],
});
