/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface TxPushSubscriptionParameters {
  /** A callback URL where to receive TxPush notifications */
  callbackUrl: string;
}

export const txPushSubscriptionParametersSchema: Schema<TxPushSubscriptionParameters> = object(
  { callbackUrl: ['callbackUrl', string()] }
);
