/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface TxVerifyInterview {
  /** A Finicity asset ID. Generated by Connect or by using the "Store Customer Pay Statement" API. */
  assetId: string;
  /** An array of Finicity account IDs to be included in the report (all accounts will be included if not set) */
  accounts?: string[];
}

export const txVerifyInterviewSchema: Schema<TxVerifyInterview> = object({
  assetId: ['assetId', string()],
  accounts: ['accounts', optional(array(string()))],
});
