/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import { TxVerifyInterview, txVerifyInterviewSchema } from './txVerifyInterview';

export interface VOIEWithInterviewData {
  /** An array of 'TxVerifyInterview' objects */
  txVerifyInterview: TxVerifyInterview[];
  /** Field to indicate whether to extract the earnings on all pay statements */
  extractEarnings?: boolean;
  /** Field to indicate whether to extract the deductions on all pay statements */
  extractDeductions?: boolean;
  /** Field to indicate whether to extract the direct deposits on all pay statements */
  extractDirectDeposit?: boolean;
}

export const vOIEWithInterviewDataSchema: Schema<VOIEWithInterviewData> = object(
  {
    txVerifyInterview: [
      'txVerifyInterview',
      array(lazy(() => txVerifyInterviewSchema)),
    ],
    extractEarnings: ['extractEarnings', optional(boolean())],
    extractDeductions: ['extractDeductions', optional(boolean())],
    extractDirectDeposit: ['extractDirectDeposit', optional(boolean())],
  }
);
