/**
 * Finicity APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

export interface VOIEWithStatementData {
  /** A list of pay statement asset IDs */
  assetIds: string[];
  /** Field to indicate whether to extract the earnings on all pay statements */
  extractEarnings?: boolean;
  /** Field to indicate whether to extract the deductions on all pay statements */
  extractDeductions?: boolean;
  /** Field to indicate whether to extract the direct deposits on all pay statements */
  extractDirectDeposit?: boolean;
}

export const vOIEWithStatementDataSchema: Schema<VOIEWithStatementData> = object(
  {
    assetIds: ['assetIds', array(string())],
    extractEarnings: ['extractEarnings', optional(boolean())],
    extractDeductions: ['extractDeductions', optional(boolean())],
    extractDirectDeposit: ['extractDirectDeposit', optional(boolean())],
  }
);
